jobs:
  build-and-test:
    macos:
      xcode: 12.5.1
    steps:
      ...
      - run:
          name: Run tests
          command: fastlane tests
          environment:
            SCAN_DEVICE: iPhone 12
            SCAN_SCHEME: TestMe
