version: 2
jobs:
  build-and-test:
    macos:
      xcode: "12.5.1"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane tests
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan